### ISSUE TITLE
Session ID could not be found in the supplied file

### ISSUE THREAD

**Issue by tux-00** [vfrazao-ns1/IEXTools#5] opened 2019-04-24 21:27 UTC
Hey,
Thank you to provide this package, this is very helpfull !

I make a script to get past data starting from 2016-12-12 but the package returns this error : 
```
Parsing IEX_data/20161212_IEXTP1_TOPS1.5.pcap ...

Traceback (most recent call last):
  File "./iex_binary_download.py", line 90, in <module>
    main()
  File "./iex_binary_download.py", line 44, in main
    parser = Parser(file_path)
  File "/home/tux/market_data_download/env/lib/python3.7/site-packages/IEXTools/IEXparser.py", line 73, in __init__
    self.session_id = self._get_session_id(file_path)
  File "/home/tux/market_data_download/env/lib/python3.7/site-packages/IEXTools/IEXparser.py", line 158, in _get_session_id
    "Session ID could not be found in the supplied file"
IEXTools.IEXHISTExceptions.ProtocolException: Session ID could not be found in the supplied file
```

Maybe this is because of the version of the TOPS binaries (1.5 only with old binaries and 1.6 with recent binaries) ?

EDIT: if I start from 2017-12-01 (version 1.6 of TOPS) I do not have this error. Do you think compatibility between these two versions can be catched easilly in the code ?

**Comment by vfrazao-ns1** [comment] 2019-04-25 04:14
The problem is actually with the protocol ID that is hardcoded in parser: https://github.com/vfrazao-ns1/IEXTools/blob/9c6b986179a5e7874b168bcc5a6bff492c3f4854/IEXTools/IEXparser.py#L66

This ID has a value of 0x8002 in version 1.5 and 0x8003 in version 1.6.

I can fix this specific issue, but I'm not sure what else changes between version 1.5 and 1.6.

**Comment by tux-00** [comment] 2019-04-25 10:33
I looked at the v1.5 specification, except networks details like multicast addresses, the data types seems to be slowly different and message format too, some entries are present in v1.6 but not in v1.5. And there are less message types in v1.5.

**Comment by vfrazao-ns1** [comment] 2019-04-29 03:33
This is fixed by the latest PR - your file should work now, you just need to specify the `tops_version=1.5` when instantiating the parser.

```python
from IEXTools import Parser
fname = "IEX_data/20161212_IEXTP1_TOPS1.5.pcap"
parser = Parser(fname, tops=True, tops_version=1.5)
```

**Closed by vfrazao-ns1** 2019-04-29 03:33 UTC
